# Generated by Codex for the Assetra AI document analyzer.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_task_comment_documentversion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIDocumentAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("mock", "Mock Demo"),
                            ("live", "Live Gemini"),
                        ],
                        default="mock",
                        max_length=20,
                    ),
                ),
                ("summary", models.TextField()),
                ("important_parties", models.JSONField(blank=True, default=list)),
                ("important_dates", models.JSONField(blank=True, default=list)),
                ("asset_details", models.JSONField(blank=True, default=dict)),
                ("risk_points", models.JSONField(blank=True, default=list)),
                ("suggested_next_action", models.TextField(blank=True)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ai_document_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analyses",
                        to="core.document",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_document_analyses",
                        to="core.firm",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["firm", "document", "created_at"],
                        name="core_aidocu_firm_id_356fa4_idx",
                    ),
                    models.Index(
                        fields=["firm", "mode", "created_at"],
                        name="core_aidocu_firm_id_e83af1_idx",
                    ),
                ],
            },
        ),
    ]
